; Projeto PlatformIO. Compile com:  pio run -e <série>
; Grave e abra o monitor:             pio run -e <série> -t upload -t monitor
[platformio]
default_envs = esp32
src_dir = main

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.312/platform-espressif32.zip
framework = espidf
monitor_speed = 115200

[env:esp32]
board = esp32dev

[env:esp32s3]
board = esp32-s3-devkitc-1

[env:esp32c2]
board = esp32-c2-devkitm-1

[env:esp32c3]
board = esp32-c3-devkitm-1

[env:esp32c5]
board = esp32-c5-devkitc-1

[env:esp32c6]
board = esp32-c6-devkitc-1

[env:esp32h2]
board = esp32-h2-devkitm-1

[env:esp32p4]
board = esp32-p4-evboard
