; Projeto PlatformIO. Compile com:  pio run -e <série>
; Grave e abra o monitor:             pio run -e <série> -t upload -t monitor
[platformio]
default_envs = esp32c6

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.312/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
; Equivale a Tools > Zigbee mode > ED e Partition Scheme > Zigbee.
board_build.partitions = zigbee.csv
build_flags = -DZIGBEE_MODE_ED -lesp_zb_api.ed -lzboss_stack.ed -lzboss_port.native

[env:esp32c6]
board = esp32-c6-devkitc-1

[env:esp32h2]
board = esp32-h2-devkitm-1
