; Projeto PlatformIO. Compile com:  pio run -e <série>
; Grave e abra o monitor:             pio run -e <série> -t upload -t monitor
[platformio]
default_envs = esp32c3

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.312/platform-espressif32.zip
framework = arduino
monitor_speed = 115200

[env:esp32c3]
board = esp32-c3-devkitm-1
